name: energy

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pandas
  - requests
  - python-dotenv
  - boto3
  - pyyaml
  - pyarrow
  - jupyter
  - ipykernel
  - matplotlib
  - pytest
  - pip
